#!/bin/sh -e
# Usage: keneric fullname mime exportPicture

fullname="$1"
mime="$2"
exportPicture="$3"

# thumbnail options by mime type
case "$mime" in
      model/stl | model/x.stl-ascii | application/sla)
            stl-thumb -s 256 "$fullname" "$exportPicture"
      ;;

      application/x-openscad)
            openscad --viewall --imgsize=256,256 --colorscheme Starnight --export-format png -o - "$fullname" | convert - -transparent black "$exportPicture"
      ;;
esac
